### ISSUE TITLE
Any plans on re-distributing the source codes?

### ISSUE THREAD

**Issue by eugenebang** [guanjq/LinkerNet#1]
Hi, 
I'm wondering if you have any plans on re-distributing the codes for the LinkerNet.
I enjoyed reading the ideas of the paper and hope to be able to study its implementation in the near future.

Thanks

**Comment by guanjq** [comment]
Hi,

I have released the code. Hope it helps!

Best,
Jiaqi

**Comment by eugenebang** [comment]
Thank you. I greatly appreciate your release of the code.
Your work is truly inspiring, and I'm excited to study how its ideas are implemented.

Best
